[build]
base = "client"
publish = ".next"
command = "yarn build"

[build.environment]
YARN_CACHE_FOLDER = "/opt/buildhome/.yarn_cache"
YARN_VERSION = "4.4.0"

[[plugins]]
package = "@netlify/plugin-nextjs"
