name: 'Version Bump'

on: workflow_dispatch

jobs:
  bump_commit:
    name: 'Bump Commit'
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.bump_script.outputs.result }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: pnpm
      - name: Install deps
        run: pnpm install:ci
      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      - name: Bump version
        run: pnpm run release

  pull_request:
    name: 'Pull Request'
    runs-on: ubuntu-latest
    needs: [bump_commit]
    steps:
      - name: Check outputs
        uses: actions/github-script@v7
        with:
          github-token: ${{ github.token }}
          script: |
            console.log(${{ needs.bump_commit.outputs.result }});
      - uses: actions/checkout@v4
        with:
          token: ${{ github.token }}
          ref: ${{ fromJSON(needs.bump_commit.outputs.result).commitBranch }}
      - name: Create Pull Request
        run: |
          gh pr create --base $BASE_BRANCH --title "$TITLE" --body "$BODY"
        env:
          BASE_BRANCH: ${{ inputs.base_branch }}
          TITLE: ${{ fromJSON(needs.bump_commit.outputs.result).title }}
          BODY: ${{ fromJSON(needs.bump_commit.outputs.result).body }}
          GITHUB_TOKEN: ${{ github.token }}
